apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: talosconfig-workers
spec:
  template:
    spec:
      generateType: worker
      configPatches:
        - op: replace
          path: /machine/install
          value:
            disk: /dev/sda
        - op: add
          path: /machine/kubelet/extraArgs
          value:
            cloud-provider: external
        - op: add
          path: /machine/kubelet/extraArgs/rotate-server-certificates
          value: "true"
