include:
  - project: 'pedropilla/pipelines'
    ref: main
    file: '/ci-templates.yml'

variables:
  APP_NAME: "infra-test"
  DOCKER_BUILD_PATH: "./github_runner/sample"
  ENVIRONMENT: "dev"

test-app:
  extends: .test-app-template

build-docker-image:
  extends: .build-docker-image-template

deploy-app:
  extends: .deploy-app-template
