apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cks-terminal-mgmt-toolz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fullstack-pw/cks-terminal-mgmt.git
    targetRevision: HEAD
    path: kustomize/overlays/toolz
  destination:
    server: https://192.168.1.30:6443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
