apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fullstack-pw/infra.git
    targetRevision: HEAD
    path: argocd-apps
    # Only include the sync-waves-demo.yaml file
    directory:
      include: 'sync-waves-demo.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
