---
- name: Configure HAProxy for Talos cluster
  hosts: "{{ haproxy_vm_name }}"
  become: true
  vars:
    haproxy_clusters:
      - name: "{{ cluster_name }}"
        frontend_port: 6443
        backend_port: 6443
        nodes: "{{ control_plane_ips | map('regex_replace', '^(.*)$', {'name': cluster_name + '-cp' + (loop.index | string), 'ip': '\\1'}) | list }}"

  tasks:
    - name: Generate dynamic HAProxy config
      set_fact:
        haproxy_cluster_config:
          name: "{{ cluster_name }}"
          frontend_port: 6443
          backend_port: 6443
          nodes: []

    - name: Build nodes list for HAProxy
      set_fact:
        haproxy_cluster_config: "{{ haproxy_cluster_config | combine({'nodes': haproxy_cluster_config.nodes + [{'name': cluster_name + '-cp' + (item + 1)|string, 'ip': control_plane_ips[item]}]}) }}"
      loop: "{{ range(0, control_plane_ips|length) | list }}"

    - name: Include HAProxy configuration playbook
      include: haproxy-config.yml
      vars:
        haproxy_clusters: [haproxy_cluster_config]