apiVersion: v1
kind: Secret
metadata:
  name: github-demo-apps-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/fullstack-pw/demo-apps
  username: not-used
  type: git
data:
  password: ""  # Will be populated by script below
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-github-repo-secret
  namespace: argocd
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: cluster-registrar
      restartPolicy: OnFailure
      containers:
        - name: sync-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e

              # Extract github_token from cluster-secrets
              GITHUB_TOKEN=$(kubectl get secret cluster-secrets -n argocd -o jsonpath='{.data.github_token}')

              # Patch github-demo-apps-repo with the token
              kubectl patch secret github-demo-apps-repo -n argocd --type='json' -p="[{\"op\": \"replace\", \"path\": \"/data/password\", \"value\": \"$GITHUB_TOKEN\"}]"

              echo "GitHub repository secret updated successfully"
