apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      #server: "https://vault.fullstack.pw:8200"
      server: "https://vault.fullstack.pw"
      path: "kv/data/cluster-secret-store/secrets"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "external-secrets"
          key: "token"
