# Secret with initconfig
apiVersion: v1
data:
  userdata: ${WORKER_USERDATA}
kind: Secret
metadata:
  labels:
    kubevirt.io/secret: ${WORKER_VM_NAME}
  name: ${WORKER_VM_NAME}
  namespace: ${SESSION_NAMESPACE}
type: Opaque
