apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: allinone
  storage:
    type: memory
  ingress:
    enabled: false  # We'll create our own ingress
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""