vault:
    kv:
        cluster-secret-store:
            secrets:
                TF_VAR_kubeconfig_path:
                    TF_VAR_kubeconfig_path: ENC[AES256_GCM,data:iKQdGVFdYXcuNDYGxuKJMHGmRm/XorGsLA==,iv:MBnzSXIVKtsCZ8BW2TufDCdtnufLOyehe3qHbtHEu40=,tag:4jj6bjfb9/ZdXeUQVkIDEw==,type:str]
sops:
    age:
        - recipient: age15vvdhaj90s3nru2zw4p2a9yvdrv6alfg0d6ea9zxpx3eagyqfqlsgdytsp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxam9qSitHbGVMdkVhckIw
            MERoZ0xHY0J6YjJLcXlpTUpXV0d2WU9ITURZCkh0NGwyay8vd0RZVTdDUU5PN1Qw
            b1JzKzRqaGlBL1g1czdQV2hkWVUrQU0KLS0tICt6MXpuQitPOFFSSXE4R2QyZThE
            Vk8vRlAvbWtIN0JNdXF0dEF4MkZjV1UKjWVj43JSl0NmAIlEZ28so46Rq0nWxmbK
            gW/+Xk+JEJ2/31PcUuk9nec2JVifV+ombohW4jkS37rTkUEW4mMTTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T09:33:02Z"
    mac: ENC[AES256_GCM,data:PlBgyp3ayMlM/nZldleMG0HP/futIRfnd8If6eA7bcnjCt+N9dWcRKv3GQo+JhDUl7twRxD45JrMUaKsU5vbZNynkPr0A0vEVRWKkK0OW4lFhm/doYNcy2afL5Igu+P2mzn3340UvsrDdBp0eBAaSx1nnlf1kQlayXebg3tQaXg=,iv:St/tm9kPyiETc/kBJJjC7yjzOuv8dEcTI+EfWdPQAcY=,tag:pdNSXIo78AeK7Q/evk5FHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
