vault:
    kv:
        cluster-secret-store:
            secrets:
                TF_VAR_kubeconfig_path:
                    TF_VAR_kubeconfig_path: ENC[AES256_GCM,data:PKG5ujGQPF2WRLon4TudSd4jPTiun1nKTg==,iv:n0tk7N9c/+qPHZE62XM+qMptR2kKGmZ/oHb2eYMucS4=,tag:K02azyLfiLmN0CdicwAwFw==,type:str]
sops:
    age:
        - recipient: age15vvdhaj90s3nru2zw4p2a9yvdrv6alfg0d6ea9zxpx3eagyqfqlsgdytsp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxam9qSitHbGVMdkVhckIw
            MERoZ0xHY0J6YjJLcXlpTUpXV0d2WU9ITURZCkh0NGwyay8vd0RZVTdDUU5PN1Qw
            b1JzKzRqaGlBL1g1czdQV2hkWVUrQU0KLS0tICt6MXpuQitPOFFSSXE4R2QyZThE
            Vk8vRlAvbWtIN0JNdXF0dEF4MkZjV1UKjWVj43JSl0NmAIlEZ28so46Rq0nWxmbK
            gW/+Xk+JEJ2/31PcUuk9nec2JVifV+ombohW4jkS37rTkUEW4mMTTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-03T07:36:28Z"
    mac: ENC[AES256_GCM,data:VsLS9NvZNw1j3LwXdxk654b8bdf0txoXZ44LfdQ5maFFoPBlflI/I/wLag13pV1/bgyxv4eV8SuKcP0nuM24skwGSRCGySNibRKg8CQr2FmpxKmEJ351Jg2LPwJjTqvebxx0cYC15n+Fo9epIm8O7WdBgkWA3zkLPk7N/RqIpjw=,iv:louP3fN83hX33KxCIqCZGP1byX0aJins4hCWG5iaTbc=,tag:APAUAr4KZChHeOaQqUZLxQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
