name: Pull Vault Secrets

on:
  push:
    branches:
      - main

jobs:
  get-secrets:
    runs-on: self-hosted
    steps:
      - name: Fetch Secret from Vault
        run: |
          export VAULT_ADDR=http://vault.vault.svc.cluster.local:8200
          export VAULT_TOKEN=$(vault write -field=token auth/kubernetes/login \
            role=github-runner \
            jwt=$(cat /run/secrets/kubernetes.io/serviceaccount/token))
          SECRET=$(vault kv get kv/dummy-test)
          echo "The secret is $SECRET"
    
