name: App Build Pipeline

on:
  push:
    # paths:
    #   - "apps/sample-app/**"

jobs:
  build-and-push:
    name: Build and Push App
    uses: fullstack-pw/pipelines/.github/workflows/build-and-push.yml@main
    with:
      app-context: "github_runner/sample"
      image-tag: "docker-registry.docker-registry.svc.cluster.local:5000/sample-app:latest"


