# name: Pull Vault Secrets

# on:
#   push:
#     branches:
#       - main

# jobs:
#   get-secrets:
#     runs-on: self-hosted
#     steps:
#       - name: Fetch Secret from Vault
#         run: |
#           export VAULT_ADDR=http://vault.vault.svc.cluster.local:8200
#           export VAULT_TOKEN=$(vault write -field=token auth/kubernetes/login \
#             role=github-runner \
#             jwt=$(cat /run/secrets/kubernetes.io/serviceaccount/token))
#           SECRET=$(vault kv get kv/dummy-test)
#           echo "The secret is $SECRET"
    
name: Build and Test Docker Image

on:
  push:

jobs:
  build:
    name: Build Docker Image
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."docker-registry.docker-registry.svc.cluster.local:5000"]
              http = true
              insecure = true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:github_runner/sample"
          push: true
          tags: docker-registry.docker-registry.svc.cluster.local:5000/test/ubuntu:latest


